title: WSIS
author:
  name: MZ UX team
  email:
description: > # this means to ignore newlines until "show_excerpts:"
  한국어 VUX 응답 패턴을 모으고 있습니다.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d 업데이트"

  # generate social links in footer
  social_links:
    # github:  jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima

# Search settings
algolia:
  application_id: HRT88OWLXS
  index_name: mzux
  search_only_api_key: 840ca575efe8e2bf9a66753a08c68aa4
    # Exclude more files from indexing
  files_to_exclude:
    - about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
